import React from 'react'; // Generated by https://quicktype.io

import {createStackNavigator} from '@react-navigation/stack';
import HomeScreen from '../src/screen/HomeScreen';
import {Movie} from '../src/interfaces/movieInterfaces';
import {DetailScreen} from '../src/screen/DetailScreen';

//aqui vamos a definir los argumentos de las rutas que siempre debemos hacer
export type RootScreenParams = {
  HomeScreen: undefined;
  DetailScreen: Movie;
};
const Stack = createStackNavigator<RootScreenParams>();

export const Navigation = () => {
  return (
    <Stack.Navigator
      screenOptions={{
        headerShown: false,
        cardStyle: {backgroundColor: 'white'},
      }}>
      <Stack.Screen name="HomeScreen" component={HomeScreen} />
      <Stack.Screen name="DetailScreen" component={DetailScreen} />
    </Stack.Navigator>
  );
};
